import {
  extractIdempotencyKey,
  findIdempotencyRecord,
  createIdempotencyRecord,
  completeIdempotencyRecord,
  failIdempotencyRecord,
  validateRequestMatch,
  generateAutoKey,
  IDEMPOTENCY_CONFIG
} from "./idempotency.js";
import { send, body, getRawBody, getParsedBody } from "./common.js";
import { createOperationLog } from "./operationLog.js";

function getRemoteAddress(req) {
  return (
    req.headers["x-forwarded-for"] ||
    req.connection?.remoteAddress ||
    req.socket?.remoteAddress ||
    ""
  );
}

function getOperatorFromAuth(auth) {
  if (!auth || !auth.authorized) return null;
  return auth.user?.username || auth.userId || null;
}

export function normalizePath(pathname) {
  return pathname
    .replace(/\/cylinders\/[^/]+\/(actions|fills)$/, "/cylinders/:id/$1")
    .replace(/\/cylinders\/[^/]+$/, "/cylinders/:id")
    .replace(/\/customers\/[^/]+\/(cylinders|deposits|orders)$/, "/customers/:id/$1")
    .replace(/\/customers\/[^/]+$/, "/customers/:id")
    .replace(/\/rental-orders\/[^/]+$/, "/rental-orders/:id")
    .replace(/\/inspection-tasks\/[^/]+\/(send|inspect|restock)$/, "/inspection-tasks/:id/$1")
    .replace(/\/inspection-tasks\/[^/]+$/, "/inspection-tasks/:id");
}

function ensureBodyLoaded(req) {
  if (req._bodyParsed === undefined) {
    return body(req);
  }
  return Promise.resolve(req._bodyParsed);
}

function getRequestBodyForHash(req) {
  const raw = getRawBody(req);
  if (raw !== null) {
    return raw;
  }
  const parsed = getParsedBody(req);
  return parsed !== null ? parsed : {};
}

function getRequestBodyForLog(req) {
  const parsed = getParsedBody(req);
  return parsed !== null ? parsed : {};
}

function sendExistingIdempotencyRecord(res, existing, { idemKey, method, pathname, bodyForHash, autoGenerated }) {
  if (existing.status === "processing") {
    return send(res, 409, {
      error: "request_in_progress",
      message: "相同幂等键的请求正在处理中，请稍后重试",
      idempotencyKey: idemKey
    });
  }
  if (existing.status === "completed") {
    if (!validateRequestMatch(existing, { method, path: pathname, body: bodyForHash })) {
      return send(res, 422, {
        error: "idempotency_key_mismatch",
        message: "幂等键已被不同参数的请求使用",
        idempotencyKey: idemKey
      });
    }
    res.setHeader("X-Idempotent-Replayed", "true");
    res.setHeader("X-Idempotency-Key", idemKey);
    if (autoGenerated) {
      res.setHeader("X-Idempotency-Key-Auto", "true");
    }
    return send(res, existing.response.statusCode, {
      ...existing.response.body,
      _idempotent: true,
      idempotencyKey: idemKey,
      operationLogId: existing.operationLogId
    });
  }
  return null;
}

export async function executeWithIdempotency(
  req,
  res,
  url,
  { auth, operationType, targetType, targetIdExtractor, operation }
) {
  await ensureBodyLoaded(req);

  const method = req.method;
  const pathname = normalizePath(url.pathname);
  const operator = getOperatorFromAuth(auth);
  const remoteAddress = getRemoteAddress(req);

  let idemKey = extractIdempotencyKey(req);
  let autoGenerated = false;

  if (!idemKey) {
    if (IDEMPOTENCY_CONFIG.REQUIRE_KEY) {
      return send(res, 400, {
        error: "idempotency_key_required",
        message: "此接口需要 Idempotency-Key 请求头"
      });
    }
    if (IDEMPOTENCY_CONFIG.AUTO_KEY_ENABLED) {
      const bodyForHash = getRequestBodyForHash(req);
      idemKey = generateAutoKey({ method, path: pathname, body: bodyForHash, operator, remoteAddress });
      autoGenerated = true;
    } else {
      return operation();
    }
  }

  const existing = await findIdempotencyRecord(idemKey);

  if (existing) {
    const bodyForHash = getRequestBodyForHash(req);
    const sent = sendExistingIdempotencyRecord(res, existing, { idemKey, method, pathname, bodyForHash, autoGenerated });
    if (sent !== null) return sent;
  }

  const bodyForHash = getRequestBodyForHash(req);
  const bodyForLog = getRequestBodyForLog(req);
  const { record: idempotencyRecord, created } = await createIdempotencyRecord(idemKey, {
    method,
    path: pathname,
    body: bodyForHash,
    operator
  });
  if (!created && idempotencyRecord) {
    const sent = sendExistingIdempotencyRecord(res, idempotencyRecord, {
      idemKey,
      method,
      pathname,
      bodyForHash,
      autoGenerated
    });
    if (sent !== null) return sent;
  }

  let beforeState = null;
  let targetId = null;
  let eventIds = [];
  let responseData = null;
  let statusCode = 200;

  const ctx = {
    setBeforeState: (state) => {
      beforeState = state;
    },
    captureEventId: (id) => {
      if (id) eventIds.push(id);
    },
    captureEventIds: (ids) => {
      if (Array.isArray(ids)) eventIds.push(...ids.filter(Boolean));
    }
  };

  try {
    const result = await operation(ctx);
    if (result && typeof result === "object") {
      if (result.statusCode) {
        statusCode = result.statusCode;
        responseData = result.body || result.data || result;
      } else {
        responseData = result;
      }
    } else {
      responseData = result;
    }

    if (targetIdExtractor) {
      targetId = targetIdExtractor(responseData);
    }
    if (!targetId && responseData && typeof responseData === "object") {
      targetId = responseData.id || null;
    }

    const afterState = responseData;

    const opLog = await createOperationLog({
      idempotencyKey: idemKey,
      operationType,
      targetType,
      targetId,
      operator,
      beforeState,
      afterState,
      requestBody: bodyForLog,
      eventIds,
      status: "success"
    });

    await completeIdempotencyRecord(idemKey, {
      statusCode,
      response: responseData,
      operationLogId: opLog.id
    });

    res.setHeader("X-Idempotency-Key", idemKey);
    if (autoGenerated) {
      res.setHeader("X-Idempotency-Key-Auto", "true");
    }
    if (responseData && typeof responseData === "object") {
      return send(res, statusCode, {
        ...responseData,
        idempotencyKey: idemKey,
        operationLogId: opLog.id
      });
    }
    return send(res, statusCode, responseData);
  } catch (err) {
    await failIdempotencyRecord(idemKey, { error: err.message });
    await createOperationLog({
      idempotencyKey: idemKey,
      operationType,
      targetType,
      targetId,
      operator,
      beforeState,
      afterState: null,
      requestBody: bodyForLog,
      eventIds,
      status: "failed",
      error: err.message
    });
    throw err;
  }
}

export async function withRawBody(req, next) {
  await ensureBodyLoaded(req);
  return next();
}
